apiVersion: v1
kind: Pod
metadata:
  labels:
    name: busybox
    role: master
  name: busybox
spec:
  containers:
    - name: busybox
      image: index.tenxcloud.com/google_containers/busybox 
      command:
      - sleep
      - "360000"
