apiVersion: v1
kind: Service
metadata:
  #service的名字为redis-master
  name: redis-master
  labels:
    name: redis-master
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  #service如何找到pod？通过selector去找label，label的key为name，value为redis-master的pod
  selector:
    name: redis-master
